# Site
repository: spacedustz/github.io
favicon: images/5.ico

# Content configuration version
version: 2

# Personal info
name: 신건우
title: Back-end Developer
email: cyberspecterr@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  spacedustz
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: cyberspecterr
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: 티스토리 기술 블로그
    icon: fas fa-globe
    url: https://iizz.tistory.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/pics.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요, 신건우입니다.<br>
  저는 전혀 다른 직종에서 일을 하다가 우연히 국비 지원 교육을 통해 2021년 3월에 IT를 접하게 되었고,<br>
  국비 지원 교육(리눅스, 네트워크 교육)을 받고 시스템 엔지니어로 취업하였습니다.<br><br>
  
  시스템 엔지니어 관련 만들어진 서비스의 유지 보수 업무를 하던 중 개발자로 방향 전환을 하게 된 계기는,<br>
  재직 당시 협력 업체의 Devops팀 업무 범위가 단순히 운영이 아닌 개발과 배포 등 전반적인 IT 업무를 하는 전문적인 모습을 보며 동경하게 되었으며,<br>
  직접 기능을 만드는 개발 업무를 배워보고자 퇴사 후 바로 개발 교육을 받고 무사히 수료를 하였습니다.<br><br>
  
  처음 배울때 논리적 & 알고리즘적인 사고에 익숙하지 않아 학습에 많은 어려움이 있었지만<br>
  점점 코드에 익숙해지고 배우면서 어려운 에러를 핸들링 하며 해결을 했을 때 느꼈던 엄청난 쾌감과,<br> 
  진심으로 즐기고 있는 제 모습을 주변 사람들이 알려주었습니다.
  <br><br>
  
  그 후, 기능 개발이 제 적성에 굉장히 잘 맞는다는 것을 느꼈으며,<br> 
  어렵고 힘들어도 즐기며 일을 할 수 있는 개발자의 길을 택하였습니다.<br><br>
  
  빠른 행동만큼 열심히 하는 것과 한번 문 것은 잘 놓지않는 끈기가 있는 성격이며, 부트캠프 수료 이후에도 지속적으로 성장중입니다.<br><br>
  짧은 기간에 얼만큼 성장 할 수 있는지는 그 사람이 어떤 사람 인지에 따라서,<br>
  엄청난 성장의 차이가 있다고 생각하며, 이 부분 만큼에 있어서 노력했다고 자신합니다.<br>
  그에 대한 근거로, 6개월의 짧은 교육 기간 동안 꾸준히 배운 것을 기록한 기술 블로그 URL을 하기 첨부 드립니다.<br><br>
  
  <strong>블로그 URL</strong> : https://iizz.tistory.com<br><br>
  
  그리고, 저는 오버 커뮤니케이션을 지향합니다.<br>
  이번 부트캠프 프로젝트에서는 팀원들과 많은 이야기를 나누지 못했고,<br>
  이는 곧 프로젝트의 결과물과 직결이 되었습니다.<br><br>
  
  보다 많은 커뮤니케이션을 통해 서로에게 피드백을 주고 받고<br>
  코드 리팩터링 등의 과정을 거쳐야 원활한 진행에 도움이 되며,<br>
  결과적으로 개개인의 성장과 더불어 프로젝트의 결과물도 좋을 것이라는 생각이 있습니다.

content:
  - title: Skills  # Title for the section
    quote: >
      공부하고 있거나, 공부했던 기술입니다.
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Languages
        description: | # this will include new lines to allow paragraphs
          * <strong>Kotlin</strong> : 현재 재직중인 곳에서 사용하고 있는 언어이며, 주력으로 사용하는 프로그래밍 언어입니다.
          <br><br>
          * <strong>Java</strong> : 백엔드 부트캠프에서 첫 프로그래밍 언어로 학습하였습니다. 객체 지향적인 코드 작성을 위해 지속적인 학습중입니다.
          <br><br>

      - layout: left
        title: Tools
        description: | # this will include new lines to allow paragraphs
          * <strong>Gradle</strong>, <strong>IntelliJ</strong> : IDE는 기본적으로 인텔리제이를 사용하며, Gradle 기반 프로젝트를 진행하였습니다. (Maven 등의 사용경험이 없습니다.)
          <br><br>
          * <strong>Git & Github</strong> : Git을 통한 협업과 코드리뷰, 형상관리 등 기본적인 사용법을 숙지하고 있습니다.
          <br><br>
          * <strong>Slack</strong> : 어플리케이션 알림 서비스로 사용중입니다.
          <br><br>
          * <strong>Jira</strong> : 프로젝트 칸반보드로 사용중입니다.
          <br><br>
          * <strong>Notion</strong> : 각종 문서들을 노션에서 다루고 있습니다.
          <br><br>
          * <strong>NaverWorks & Workplace</strong> : Workplace를 통한 근태관리, Naver Works를 통한 사내 팀원들과의 메신저 역할로 사용중입니다.

      - layout: left
        title: Frameworks
        description: | # this will include new lines to allow paragraphs
          * <strong>Spring</strong> : Spring Boot를 Base로 기능 개발에 사용합니다.
            - <strong>Spring MVC & Spring Data JPA</strong> : 기본적인 MVC 패턴과 Spring Boot기반의 ORM인 JPA & Hibernate를 이용하여 Restful API 구축을 메인으로 지속적인 학습중입니다.
            - <strong>Spring Security</strong> : Authentication & Authorization에 대한 이해와 토큰 기반 인증 방식인 JWT를 어플리케이션에 적용해보았습니다.
            - <strong>Spring Cloud Config</strong> : 면접 준비를 위한 디스코드 봇을 만들던 중 민감 정보인 토큰 값의 로컬관리 외의 방법을 찾다가 구축을 해보게 되었습니다.
            - <strong>Spring Cloud Gateway</strong> : 마이크로 서비스 호출에 대한 ACL 적용과 트래픽 라우팅 경험 학습을 위한 API Gateway를 간단하게 구현해보았습니다.
            - <strong>OAuth2</strong> : Third-Party API에 사용자 인증 처리를 위임함으로써 서버의 리소스를 줄이며 간단한 인증 처리를 구현을 해보았습니다.
          <br><br>

      - layout: left
        title: DataBase
        description: | # this will include new lines to allow paragraphs
          * <strong>MySQL</strong> : RDBMS에 대해 기본적인 내용을 알고 있습니다.<br>
          Spring Data JPA에서 QueryDSL을 이용한 JPQL 쿼리 튜닝을 통한 데이터 핸들링 경험이 있습니다.
          <br><br>
          * <strong>FireBase</strong> : Firebase : Firebase 데이터베이스와 FCM을 통한 메시지 & 채팅 이벤트 처리 경험이 있습니다.
          <br><br>

      - layout: left
        title: Ops
        description: | # this will include new lines to allow paragraphs
          * <strong>AWS</strong> : EC2 & IAM & CodePipeline & CodeDeploy & RDS & S3 등의 서비스를 사용하여 CI/CD를 구축한 경험이 있습니다.
          <br><br>
          * <strong>Github Actions</strong> : Githhub Actions가 AWS S3에 빌드 결과물을 전송하면 S3가 이를 CodeDeploy에게 전달하여 EC2에 배포 및 실행하는 플로우로 CI/CD를 구축하였습니다.
          <br><br>
          * <strong>Docker</strong> : 컨테이너 이미지를 통한 버전관리와 Private Registry를 통해 이미지를 관리하고 Dockerfile을 빌드 하는 등 기본적인 사용법을 숙지하고 있습니다.
          <br><br>
          * <strong>Kubernetes</strong> : 기본적인 클러스터 생성
            - kubespray, kubeadm 2가지 방법을 이용한 Master & Slaves 클러스터 생성 경험이 있습니다.
            - 로컬에 테스트 클러스터를 생성해 Node와 Pod의 Lifecycle 관리를 실습해보았습니다.
            - 쿠버네티스 대시보드를 구현해 SSL 인증서를 연동하는 등 독학으로 연습하며 다루어 보았습니다.
            - 메트릭 서비스인 Prometheus와 데이터 시각화 툴인 Grapana를 연동하는 등 독학으로 실습한 경험이 있습니다. (실무적용 경험 X)

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 부트캠프 메인 프로젝트
        icon: fab fa-github
        link: http://project-teatime-dev.s3-website.ap-northeast-2.amazonaws.com/
        caption: 2023.01 - 2023.02
        quote: >
          이젠 상담도 그룹으로 하자, 티타임.
        description: | # this will include new lines to allow paragraphs
          이 프로젝트는 부트 캠프에서 진행한 메인 프로젝트입니다. 
          프론트엔드3 백엔드3 총 6명이서 진행하였으며, 기존 상담어플들의 그룹상담 기능의 부재로 인해 기획을 하게 되었습니다. 
          <br><br>
          프로젝트에서 설계부터 기본적인 CRUD와 배포에 집중했습니다.<br>
          아직 실무적으로 부족하다고 생각해서 중요한 것은 배웠던걸 기본적으로 잘 접목하여 작지만 강한 어플리케이션을 만들어보고 싶었습니다. <br><br>
          
          기본 구현을 끝낸 뒤 <strong>성능 최적화를 위해 코드 리팩터링을</strong>하는 도중
          <strong>N+1 문제</strong>, <strong>순환참조 & 연관관계</strong> 등의 여러 상황이 발생하여,<br><br>
          
          적절한 Fetch 전략과 Fetch Join을 이용한 쿼리 튜닝과 프록시 객체의 처리,<br>
          JPA의 OSIV 옵션을 false로 설정하여 트랜잭션 종료 시 DB 커넥션 회수로 인한 성능 향상,<br>
          엔티티간 불필요한 양방향 연관관계도 단방향으로 끊으면서 어플리케이션의 성능을 위한 리팩터링을 하였고<br>
          Linux 관련 실무를 접해본 제가 배포를 도맡아 어플리케이션 배포방법 등의 논의를 거쳐 Github Actions와 AWS를 이용해 파이프라인을 구축했습니다.

  #  - title: Experience # Title for the section
  #    layout: list # Type of content section (list/text)
  #    content:
  #      - layout: left
  #        title: The Boring Company
  #        link: boringcompany.com
  #        # link_text: boringcompany.com
  #        sub_title: Senior Network System Administrator
  #        caption: November 2017 - Present
  #        quote: >
  ##          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #        description: | # this will include new lines to allow paragraphs
  #            test

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 우주펫
        caption: 2023.04 ~ 현재
        sub_title: 개발팀 백엔드 팀원
        quote: | # this will include new lines to allow paragraphs
          지역 기반 반려인 소셜 디스커버리 & 돌봄 교환 서비스 기업으로 22년 초 강남지역에 첫 출시 후,<br>
          현재 수도권 전체 지역에 서비스를 제공하고 있으며, 초기 토스 & 페이스북 보다 높은 리텐션을 보여주고 있는 어플리케이션입니다.<br><br>
          
          Kotlin & Spring Boot 기반 반려 커뮤니티 서비스의 전반적인 백엔드 파트의 기능 개발을 담당하고 있습니다.
      - layout: top-middle
        title: 코드스테이츠
        caption: 2022.08 - 2023.02
        sub_title: 백엔드 부트캠프 41기
        quote: | # this will include new lines to allow paragraphs
          Java를 활용해 MVC 패턴과 Spring Boot기반의 ORM인 JPA & Hibernate를 이용하여 Restful API 구축을 메인으로 학습하였습니다.
      - layout: top-middle
        title: 고은정보기술
        caption: 2021.10 - 2022.07
        sub_title: 기술지원팀/주임
        quote: | # this will include new lines to allow paragraphs
          - HP & DELL 서버 구축 및 마운트 (Linux & Windows 서버)<br>
          - 서버 원격 유지보수<br>
          - 서버 간 데이터 이전 작업<br>
          - SSL 발급<br>
          - UTM & SPAM & NAS 등 마운트, 보안 설정 작업<br>
          - 보안 취약점 분석 & 평가<br>
          - Fortinet 방화벽 마운트 & 설정<br>
          - Docker 컨테이너 Lifecycle 관리 및 모니터링
      - layout: top-middle
        title: 한국디지털융합 직업전문학교
        caption: 2021.03 - 2021.09
        sub_title: ICT(Information&CommunicationTechnology)보안은 시스템,네트워크 등 정보통신과 관련된 기반지식을 가지고 조직의 정보자산을 관리적, 물리적, 기술적 보안관점에서 효율적으로 보호하는 능력을 함양
        quote: | # this will include new lines to allow paragraphs
          리눅스와 네트워크의 대한 기본적인 서버 지식들, L2,L3 스위치와 서버 구축에 대해 학습하였습니다.
      - layout: top-middle
        title: 덕수고등학교
        caption: 2010.03 - 2013.03
        sub_title: 문과
        quote: | # this will include new lines to allow paragraphs
  - title: Licenses
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [22.06 취득]  <strong>리눅스마스터 1급</strong> - (사)한국정보통신진흥협회 
      <br><br>
      - [22.02 취득]  <strong>CKA: Certified Kubernetes Administrator</strong> - Cloud Native Computing Foundation
      <br><br>
      - [21.10 취득]  <strong>정보처리기능사</strong> - 한국산업인력공단
      <br><br>
      - [21.09 취득]  <strong>정보기기운용기능사</strong> - 한국산업인력공단
      <br><br>
      - [21.07 취득]  <strong>리눅스마스터 2급</strong> - (사)한국정보통신진흥협회
      <br><br>
      - [21.06 취득]  <strong>네트워크관리사 2급</strong> - 한국정보통신자격협회
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag